version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/airbridge-go-bypass-was
hooks:
  BeforeInstall:
    - location: res/deploy/before-install.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: res/deploy/after-install.sh
      timeout: 120
      runas: root
