package webapp

const (
	CARD_LOAD   = 1
	CARD_FOCUS  = 2
	CARD_CLICK  = 3
	CARD_BLUR   = 4
	CARD_EXIT   = 5
	CARD_RELOAD = 6
)

const (
	MOBILE_LAUNCH                          = 101
	MOBILE_GOAL                            = 102
	MOBILE_BACKGROUND                      = 103
	MOBILE_INSTALL                         = 104
	MOBILE_TRACING_VIEW                    = 105
	MOBILE_TRACING_ACTION                  = 106
	MOBILE_FOREGROUND                      = 107
	MOBILE_LAUNCH_WITHOUT_TID              = 108
	MOBILE_GOAL_WITHOUT_TID                = 109
	MOBILE_INSTALL_WITHOUT_DEFERRED_HASH   = 110
	MOBILE_INSTALL_WITH_AIRBRIDGE_REFERRER = 120

	// NEW MOBILE EVENT CATEGORY FOR V2 API
	MOBILE_VIEW__APP_SESSION_LAUNCH           = 9160
	MOBILE_VIEW__APP_SESSION_INSTALL          = 9161
	MOBILE_VIEW__APP_SESSION_DEEPLINK_LAUNCH  = 9162
	MOBILE_VIEW__APP_SESSION_DEEPLINK_INSTALL = 9163
	MOBILE_VIEW__APP_SESSION_FOREGROUND       = 9166

	MOBILE_VIEW__APP_PAGEVIEW        = 9164
	MOBILE_VIEW__APP_FOREGROUND      = 9165
	MOBILE_VIEW__APP_LAUNCH          = 9167
	MOBILE_VIEW__APP_DEEPLINK_LAUNCH = 9168

	MOBILE_REACH__APP_EXIT          = 9260
	MOBILE_REACH__APP_TO_WEB        = 9262
	MOBILE_REACH__APP_TO_APP        = 9266
	MOBILE_REACH__APP_TO_BACKGROUND = 9269 // MOBILE BACKGROUND EVENT
	MOBILE_GOAL__APP                = 9360
)
